# Generated by Django 3.1.3 on 2021-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('invitation_link', models.CharField(blank=True, max_length=500, null=True)),
                ('connection_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('company', models.CharField(default='Electronic Company', max_length=120)),
                ('division', models.CharField(max_length=120)),
                ('jobtitle', models.CharField(max_length=120)),
                ('connection_id', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_id', models.IntegerField(blank=True, null=True)),
                ('issued', models.DateField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('thread_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
